luiz carlos 06/11/23 - finalizado semana
Categoria
 - método lista -ok
- método cadastra -ok

Cliente
- método lista -ok
- método cadastra (esta dando erro {

" Hibernate:
    select
        c1_0.id,
        c1_0.cpf,
        c1_0.bairro,
        c1_0.cidade,
        c1_0.complemento,
        c1_0.estado,
        c1_0.numero,
        c1_0.rua,
        c1_0.nome,
        c1_0.telefone,
        c1_0.usuario_id
    from
        cliente c1_0
Hibernate:
    select
        u1_0.id,
        u1_0.login,
        u1_0.senha
    from
        usuario u1_0
    where
        u1_0.id=?
Hibernate:
    select
        u1_0.id,
        u1_0.login,
        u1_0.senha
    from
        usuario u1_0
    where
        u1_0.id=?
Hibernate:
    select
        u1_0.id,
        u1_0.login,
        u1_0.senha
    from
        usuario u1_0
    where
        u1_0.id=?
DadosNovoCliente[nome=null, cpf=null, telefone=null, endereco=DadosNovoEndereco[rua=null, numero=null, complemento=null, bairro=null, cidade=null, estado=null]]
Hibernate:
    insert
    into
        cliente
        (cpf, bairro, cidade, complemento, estado, numero, rua, nome, telefone, usuario_id)
    values
        (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-11-06T17:00:29.674-03:00  WARN 31072 --- [io-8080-exec-10] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1048, SQLState: 23000
2023-11-06T17:00:29.674-03:00 ERROR 31072 --- [io-8080-exec-10] o.h.engine.jdbc.spi.SqlExceptionHelper   : Column 'cpf' cannot be null
2023-11-06T17:00:29.684-03:00 ERROR 31072 --- [io-8080-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]] with root cause

java.sql.SQLIntegrityConstraintViolationException: Column 'cpf' cannot be null
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[mysql-connector-j-8.0.31.jar!/:8.0.31]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.0.31.jar!/:8.0.31] "
}
 )

Produto
- método lista - (não exibe na tela, não sei porque  )
- método cadastra - não foi implementado, mas já foi criado o método